name: Build Kivy Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.33
          pip install kivy kivymd requests beautifulsoup4 pandas geocoder geopy unidecode plyer pillow

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: bin/*.apk

